deps.fabric_api = 0.92.6+1.20.1
deps.modmenu = 7.2.2
deps.elementa.mc = 1.20.1

# Minecraft dependency for fabric.mod.json
mod.mc_dep = <=1.20.1 >=1.20

# Release title for Modrinth
mod.mc_title = Minecraft 1.20 and .1

# Space-separated compatible versions for publishing
mod.mc_targets = 1.20.1 1.20