#
# SPDX-License-Identifier: MIT
# Copyright (c) 2025 rotgruengelb, and stonecutter-mod-template contributors
# Copyright (c) 2025 murder_spagurder
# Copyright (c) 2026 Greenman999
# See the LICENSE file in the project root for license terms.
#

org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

mod.id=fullbright
mod.name=Fullbright
mod.group=de.greenman999
mod.version=3.2.0
mod.channel_tag=-alpha.1
mod.authors=Greenman999
mod.contributors=
mod.license=GPL-3.0-or-later
mod.description=This is a fabric mod that adds a fullbright feature to the game.
mod.sources_url=https://github.com/Greeenman999/fullbright
mod.homepage_url=https://modrinth.com/mod/fullbright
mod.issues_url=https://github.com/Greeenman999/fullbright/issues
mod.discord_url=https://discord.gg/NYXwdwMUrq

deps.minecraft=[VERSIONED]
deps.fabric-api=[VERSIONED]
deps.neoforge=[VERSIONED]
deps.modmenu=[VERSIONED]
deps.parchment=[VERSIONED]
deps.universalcraft-mc=[VERSIONED]

deps.universalcraft=472
deps.elementa=714
deps.fabric-kotlin=1.13.7+kotlin.2.2.21
deps.configurate=4.2.0
deps.commons-text=1.14.0

publish.modrinth=VyxkIxCd
publish.curseforge=
publish.github=true