deps.fabric_api = 0.77.0+1.19.2
deps.modmenu = 4.1.2
deps.elementa.mc = 1.19.2

# Minecraft dependency for fabric.mod.json
mod.mc_dep = <=1.19.2 >=1.19

# Release title for Modrinth
mod.mc_title = Minecraft 1.19, .1 and .2

# Space-separated compatible versions for publishing
mod.mc_targets = 1.19.2 1.19.1 1.19