deps.fabric_api = 0.138.3+1.21.10
deps.modmenu = 16.0.0-rc.1
deps.elementa.mc = 1.21.9

# Minecraft dependency for fabric.mod.json
mod.mc_dep = <=1.21.10 >=1.21.9

# Release title for Modrinth
mod.mc_title = Minecraft 1.21.10 and .9

# Space-separated compatible versions for publishing
mod.mc_targets = 1.21.10 1.21.9