#
# SPDX-License-Identifier: MIT
# Copyright (c) 2025 rotgruengelb, and stonecutter-mod-template contributors
# Copyright (c) 2026 Greenman999
# See the LICENSE file in the project root for license terms.
#

deps.minecraft=26.1
deps.fabric-api=0.144.3+26.1
deps.modmenu=18.0.0-alpha.8
deps.universalcraft-mc=26.1

publish.additionalVersions=